# Taps
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/bundle'
tap 'nicoverbruggen/homebrew-cask'
tap 'shivammathur/php'

# Binaries
brew 'ack'
brew 'awscli'
brew 'bash' # Latest Bash version
brew 'bat' # Used for spatie/visit
brew 'coreutils' # Those that come with macOS are outdated
brew 'entr'
brew 'ffmpeg'
brew 'findutils'
brew 'fzf'
brew 'gh'
brew 'git'
brew 'git-flow'
brew 'gnupg'
brew 'grep'
brew 'gstat'
brew 'hub'
brew 'htop'
brew 'httpie'
brew 'jq' # Used for spatie/visit
brew 'mackup'
brew 'mas' # Mac App Store manager
brew 'mc' # midnight-commander
brew 'pkg-config' # https://github.com/driesvints/dotfiles/issues/20
brew 'rg' # ripgrep
brew 'stow'
brew 'svn' # Needed to install fonts
brew 'tree'
brew 'vim'
brew 'wget'
brew 'zlib' # Needed for Memcached
brew 'zoxide'

# Spatie Medialibrary
brew 'jpegoptim'
brew 'optipng'
brew 'pngquant'
brew 'svgo'
brew 'gifsicle'

# Development
brew 'php'
brew 'php@8.2'
brew 'php@8.1'
brew 'php@8.0'
brew 'composer'
brew 'imagemagick'
brew 'meilisearch'
brew 'node'

# Apps casks
cask '1password'
cask 'airbuddy'
cask 'bartender'
cask 'docker'
cask 'dropbox'
cask 'firefox'
cask 'folx'
cask 'github'
cask 'gitup'
cask 'google-chrome'
cask 'handbrake'
cask 'hidock'
cask 'iina'
cask 'imagealpha'
cask 'imageoptim'
cask 'insomnia'
cask 'istat-menus'
cask 'iterm2'
cask 'karabiner-elements'
cask 'latest'
cask 'microsoft-excel'
cask 'microsoft-teams'
cask 'microsoft-outlook'
cask 'microsoft-word'
cask 'monitorcontrol'
cask 'moom'
cask 'obsidian'
cask 'omnidisksweeper'
cask 'postman'
cask 'phpstorm'
cask 'rapidapi'
cask 'raycast'
cask 'screens'
cask 'screens-connect'
cask 'subler'
cask 'sublime-text'
cask 'tableplus'
cask 'the-unarchiver'
cask 'tinkerwell'
cask 'tor-browser'
cask 'transmission'
cask 'transmit'
cask 'tunnelblick'
cask 'tuple'
# cask 'vagrant' # sudo softwareupdate --install-rosetta
cask 'vidl'
# cask 'virtualbox' # Might need to allow access in Security settings
cask 'visual-studio-code'
cask 'vlc'
cask 'xit'

# Quicklook
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'quicklook-csv'
cask 'qlvideo'

# Fonts
cask 'font-hack-nerd-font'
cask 'font-hack'
cask 'font-lato'
cask 'font-open-sans'
cask 'font-roboto'
cask 'font-source-code-pro-for-powerline'
cask 'font-source-code-pro'
cask 'font-source-sans-pro'
cask 'font-source-serif-pro'
cask 'font-fira-code'

# Mac App Store
mas '1Blocker - Ad Blocker', id: 1365531024
mas 'Amphetamine', id: 937984704
mas 'Boop', id: 1518425043
mas 'Byword', id: 420212497
mas 'Coin Tick - Menu Bar Crypto', id: 1141688067
mas 'Dropzone 4', id: 1485052491
mas 'Gestimer', id: 990588172
mas 'Glance - Quick Look Code Files', id: 1564688210
mas 'HazeOver • Distraction Dimmer', id: 430798174
mas 'LookUp: English dictionary', id: 872564448
mas 'Moom', id: 419330170
mas 'Numbers', id: 409203825
mas 'Paste - Clipboard Manager', id: 967805235
mas 'PCalc', id: 403504866
mas 'Pixave', id: 924891282
mas 'Pixelmator Pro', id: 1289583905
mas 'Redacted', id: 984968384
mas 'Reeder 5.', id: 1529448980
mas 'Sequel Ace', id: 1518036000
mas 'Soulver 2', id: 413965349
mas 'Tailscale', id: 1475387142
mas 'xScope 4', id: 889428659
mas 'Yoink - Improved Drag and Drop', id: 457622435
# mas 'The Unarchiver', id: 425424353
# mas 'Keynote', id: 409183694
# mas 'Things', id: 904280696
