return {
  -- Mason package manager
  {
    "mason-org/mason.nvim",
    opts = {
      ensure_installed = {
        "actionlint",
        "ansible-language-server",
        "ansible-lint",
        "antlers-language-server",
        "black",
        "bash-language-server",
        "blade-formatter",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "dot-language-server",
        "emmet-ls",
        "eslint_d",
        "flake8",
        "hadolint",
        "html-lsp",
        "intelephense",
        "nginx-language-server",
        "php-debug-adapter",
        "phpstan",
        "pint",
        "prettierd",
        "pyright",
        "rustywind",
        "shellcheck",
        "shfmt",
        "stylua",
        "tailwindcss-language-server",
      },
    },
  },

  -- Mason tool installer - enables headless install/update of Mason packages
  -- Provides :MasonToolsInstall, :MasonToolsUpdate, :MasonToolsClean commands
  {
    "WhoIsSethDaniel/mason-tool-installer.nvim",
    dependencies = { "mason.nvim" },
    event = "VeryLazy",
    opts = {
      ensure_installed = {
        "actionlint",
        "ansible-language-server",
        "ansible-lint",
        "antlers-language-server",
        "black",
        "bash-language-server",
        "blade-formatter",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "dot-language-server",
        "emmet-ls",
        "eslint_d",
        "flake8",
        "hadolint",
        "html-lsp",
        "intelephense",
        "nginx-language-server",
        "php-debug-adapter",
        "phpstan",
        "pint",
        "prettierd",
        "pyright",
        "rustywind",
        "shellcheck",
        "shfmt",
        "stylua",
        "tailwindcss-language-server",
      },
      auto_update = false, -- Don't auto-update on startup (can be slow)
      run_on_start = true, -- Install missing tools on startup
    },
  },
}
